//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning_Platform.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class e_learning_dbEntities : DbContext
    {
        public e_learning_dbEntities()
            : base("name=e_learning_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<course> courses { get; set; }
    
        [DbFunction("e_learning_dbEntities", "Login")]
        public virtual IQueryable<Login_Result> Login(string gmail, Nullable<long> mobile, string pass)
        {
            var gmailParameter = gmail != null ?
                new ObjectParameter("gmail", gmail) :
                new ObjectParameter("gmail", typeof(string));
    
            var mobileParameter = mobile.HasValue ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(long));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Login_Result>("[e_learning_dbEntities].[Login](@gmail, @mobile, @pass)", gmailParameter, mobileParameter, passParameter);
        }
    }
}
