//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int s_id { get; set; }
        public string father_name { get; set; }
        public string mother_name { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual course course { get; set; }
    }
}
