//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int tacher_id { get; set; }
        public string qualification { get; set; }
        public string subject { get; set; }
        public string gender { get; set; }
        public bool isActive { get; set; }
        public int user_id { get; set; }
        public int department { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public string Status { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual user user { get; set; }
    }
}
